package com.example.mapper;

import com.example.pojo.Dept;
import java.util.List;

public interface DeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPT
     *
     * @mbg.generated Thu Feb 04 11:45:17 CST 2021
     */
    int deleteByPrimaryKey(Integer deptno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPT
     *
     * @mbg.generated Thu Feb 04 11:45:17 CST 2021
     */
    int insert(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPT
     *
     * @mbg.generated Thu Feb 04 11:45:17 CST 2021
     */
    Dept selectByPrimaryKey(Integer deptno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPT
     *
     * @mbg.generated Thu Feb 04 11:45:17 CST 2021
     */
    List<Dept> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPT
     *
     * @mbg.generated Thu Feb 04 11:45:17 CST 2021
     */
    int updateByPrimaryKey(Dept record);
}