package com.example.pojo;

import java.util.Date;

public class Emp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMP.EMPNO
     *
     * @mbg.generated Thu Feb 04 11:45:17 CST 2021
     */
    private Integer empno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMP.ENAME
     *
     * @mbg.generated Thu Feb 04 11:45:17 CST 2021
     */
    private String ename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMP.JOB
     *
     * @mbg.generated Thu Feb 04 11:45:17 CST 2021
     */
    private String job;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMP.MGR
     *
     * @mbg.generated Thu Feb 04 11:45:17 CST 2021
     */
    private Integer mgr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMP.HIREDATE
     *
     * @mbg.generated Thu Feb 04 11:45:17 CST 2021
     */
    private Date hiredate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMP.SAL
     *
     * @mbg.generated Thu Feb 04 11:45:17 CST 2021
     */
    private Integer sal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMP.COMM
     *
     * @mbg.generated Thu Feb 04 11:45:17 CST 2021
     */
    private Integer comm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMP.DEPTNO
     *
     * @mbg.generated Thu Feb 04 11:45:17 CST 2021
     */
    private Integer deptno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMP.EMPNO
     *
     * @return the value of EMP.EMPNO
     *
     * @mbg.generated Thu Feb 04 11:45:17 CST 2021
     */
    public Integer getEmpno() {
        return empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMP.EMPNO
     *
     * @param empno the value for EMP.EMPNO
     *
     * @mbg.generated Thu Feb 04 11:45:17 CST 2021
     */
    public void setEmpno(Integer empno) {
        this.empno = empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMP.ENAME
     *
     * @return the value of EMP.ENAME
     *
     * @mbg.generated Thu Feb 04 11:45:17 CST 2021
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMP.ENAME
     *
     * @param ename the value for EMP.ENAME
     *
     * @mbg.generated Thu Feb 04 11:45:17 CST 2021
     */
    public void setEname(String ename) {
        this.ename = ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMP.JOB
     *
     * @return the value of EMP.JOB
     *
     * @mbg.generated Thu Feb 04 11:45:17 CST 2021
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMP.JOB
     *
     * @param job the value for EMP.JOB
     *
     * @mbg.generated Thu Feb 04 11:45:17 CST 2021
     */
    public void setJob(String job) {
        this.job = job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMP.MGR
     *
     * @return the value of EMP.MGR
     *
     * @mbg.generated Thu Feb 04 11:45:17 CST 2021
     */
    public Integer getMgr() {
        return mgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMP.MGR
     *
     * @param mgr the value for EMP.MGR
     *
     * @mbg.generated Thu Feb 04 11:45:17 CST 2021
     */
    public void setMgr(Integer mgr) {
        this.mgr = mgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMP.HIREDATE
     *
     * @return the value of EMP.HIREDATE
     *
     * @mbg.generated Thu Feb 04 11:45:17 CST 2021
     */
    public Date getHiredate() {
        return hiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMP.HIREDATE
     *
     * @param hiredate the value for EMP.HIREDATE
     *
     * @mbg.generated Thu Feb 04 11:45:17 CST 2021
     */
    public void setHiredate(Date hiredate) {
        this.hiredate = hiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMP.SAL
     *
     * @return the value of EMP.SAL
     *
     * @mbg.generated Thu Feb 04 11:45:17 CST 2021
     */
    public Integer getSal() {
        return sal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMP.SAL
     *
     * @param sal the value for EMP.SAL
     *
     * @mbg.generated Thu Feb 04 11:45:17 CST 2021
     */
    public void setSal(Integer sal) {
        this.sal = sal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMP.COMM
     *
     * @return the value of EMP.COMM
     *
     * @mbg.generated Thu Feb 04 11:45:17 CST 2021
     */
    public Integer getComm() {
        return comm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMP.COMM
     *
     * @param comm the value for EMP.COMM
     *
     * @mbg.generated Thu Feb 04 11:45:17 CST 2021
     */
    public void setComm(Integer comm) {
        this.comm = comm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMP.DEPTNO
     *
     * @return the value of EMP.DEPTNO
     *
     * @mbg.generated Thu Feb 04 11:45:17 CST 2021
     */
    public Integer getDeptno() {
        return deptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMP.DEPTNO
     *
     * @param deptno the value for EMP.DEPTNO
     *
     * @mbg.generated Thu Feb 04 11:45:17 CST 2021
     */
    public void setDeptno(Integer deptno) {
        this.deptno = deptno;
    }

    @Override
    public String toString() {
        return "Emp{" +
                "empno=" + empno +
                ", ename='" + ename + '\'' +
                ", job='" + job + '\'' +
                ", mgr=" + mgr +
                ", hiredate=" + hiredate +
                ", sal=" + sal +
                ", comm=" + comm +
                ", deptno=" + deptno +
                '}';
    }
}